theme: jekyll-theme-cayman
title: Hello! I am Swarali.

## Welcome to my homepage.


I am an undergraduate student in Physics at the Indian Institute of Science Education and Research, Thiruvananthapuram. I am currently working on a project in cosmology.
