theme: jekyll-theme-cayman
title: Swarali Patil.

## Hello!
### Welcome to my homepage.


I am an undergraduate student in Physics at the Indian Institute of Science Education and Research, Thiruvananthapuram.
I am currently working on a project in cosmology.
